version: '3'
services:
  postgres-db:
    image: postgres:latest
    container_name: currency-conversion-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: "currency"
      POSTGRES_USER: "currency"
      POSTGRES_PASSWORD: "currency"
    volumes:
      - currency-volume:/var/lib/postgresql/data
    networks:
      - currency-network
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: currency-conversion-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "6001:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=currency-conversion
      - RABBITMQ_DEFAULT_PASS=currency-conversion
    networks:
      - currency-network
  app:
    container_name: currency-conversion-service
    build: .
    networks:
      - currency-network
    ports:
      - "4001:4001"
    depends_on:
      - postgres-db
    environment:
      - APP_ENV=local
      - DB_HOST=currency-conversion-db
      - DB_PORT=5432
      - SERVER_PORT=4001
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=currency-conversion-rabbitmq
volumes:
  currency-volume:

networks:
  currency-network: