// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eneskzlcn/currency-conversion-service/app/exchange (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/eneskzlcn/currency-conversion-service/app/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetExchangeValuesForGivenCurrencies mocks base method.
func (m *MockRepository) GetExchangeValuesForGivenCurrencies(arg0 context.Context, arg1, arg2 string) (entity.Exchange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeValuesForGivenCurrencies", arg0, arg1, arg2)
	ret0, _ := ret[0].(entity.Exchange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeValuesForGivenCurrencies indicates an expected call of GetExchangeValuesForGivenCurrencies.
func (mr *MockRepositoryMockRecorder) GetExchangeValuesForGivenCurrencies(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeValuesForGivenCurrencies", reflect.TypeOf((*MockRepository)(nil).GetExchangeValuesForGivenCurrencies), arg0, arg1, arg2)
}

// IsCurrencyExists mocks base method.
func (m *MockRepository) IsCurrencyExists(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCurrencyExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCurrencyExists indicates an expected call of IsCurrencyExists.
func (mr *MockRepositoryMockRecorder) IsCurrencyExists(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCurrencyExists", reflect.TypeOf((*MockRepository)(nil).IsCurrencyExists), arg0, arg1)
}

// SetUserActiveExchangeRateOffer mocks base method.
func (m *MockRepository) SetUserActiveExchangeRateOffer(arg0 context.Context, arg1 entity.UserActiveExchangeOffer) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActiveExchangeRateOffer", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActiveExchangeRateOffer indicates an expected call of SetUserActiveExchangeRateOffer.
func (mr *MockRepositoryMockRecorder) SetUserActiveExchangeRateOffer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActiveExchangeRateOffer", reflect.TypeOf((*MockRepository)(nil).SetUserActiveExchangeRateOffer), arg0, arg1)
}
