// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eneskzlcn/currency-conversion-service/app/exchange (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	exchange "github.com/eneskzlcn/currency-conversion-service/app/exchange"
	model "github.com/eneskzlcn/currency-conversion-service/app/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateExchangeRateOffer mocks base method.
func (m *MockRepository) CreateExchangeRateOffer(arg0 context.Context, arg1 exchange.CreateExchangeRateOfferDTO) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExchangeRateOffer", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExchangeRateOffer indicates an expected call of CreateExchangeRateOffer.
func (mr *MockRepositoryMockRecorder) CreateExchangeRateOffer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExchangeRateOffer", reflect.TypeOf((*MockRepository)(nil).CreateExchangeRateOffer), arg0, arg1)
}

// GetExchangeValuesForGivenCurrencies mocks base method.
func (m *MockRepository) GetExchangeValuesForGivenCurrencies(arg0 context.Context, arg1, arg2 string) (model.CurrencyExchangeValues, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeValuesForGivenCurrencies", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.CurrencyExchangeValues)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeValuesForGivenCurrencies indicates an expected call of GetExchangeValuesForGivenCurrencies.
func (mr *MockRepositoryMockRecorder) GetExchangeValuesForGivenCurrencies(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeValuesForGivenCurrencies", reflect.TypeOf((*MockRepository)(nil).GetExchangeValuesForGivenCurrencies), arg0, arg1, arg2)
}

// IsCurrencyExists mocks base method.
func (m *MockRepository) IsCurrencyExists(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCurrencyExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCurrencyExists indicates an expected call of IsCurrencyExists.
func (mr *MockRepositoryMockRecorder) IsCurrencyExists(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCurrencyExists", reflect.TypeOf((*MockRepository)(nil).IsCurrencyExists), arg0, arg1)
}
