// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eneskzlcn/currency-conversion-service/app/exchange (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	exchange "github.com/eneskzlcn/currency-conversion-service/app/exchange"
	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// PrepareExchangeRateOffer mocks base method.
func (m *MockService) PrepareExchangeRateOffer(arg0 context.Context, arg1 int, arg2 exchange.ExchangeRateRequest) (exchange.ExchangeRateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareExchangeRateOffer", arg0, arg1, arg2)
	ret0, _ := ret[0].(exchange.ExchangeRateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareExchangeRateOffer indicates an expected call of PrepareExchangeRateOffer.
func (mr *MockServiceMockRecorder) PrepareExchangeRateOffer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareExchangeRateOffer", reflect.TypeOf((*MockService)(nil).PrepareExchangeRateOffer), arg0, arg1, arg2)
}
