JWT_AT_PRIVATE_KEY: "MySecretKey"
JWT_AT_EXPIRATION_MIN: 400

DB_USERNAME: "currency"
DB_PASSWORD: "currency"
DB_NAME: "currency"
DB_HOST: "localhost"
DB_PORT: "5435"

SERVER_PORT: "4000"

RABBITMQ_USERNAME: "currency-conversion"
RABBITMQ_PASSWORD: "currency-conversion"
RABBITMQ_PORT: "6001"
RABBITMQ_HOST: "localhost"
RABBITMQ_CURRENCY_CONVERTED_QUEUE: "currency-converted"