// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eneskzlcn/currency-conversion-service/app/conversion (interfaces: WalletService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWalletService is a mock of WalletService interface.
type MockWalletService struct {
	ctrl     *gomock.Controller
	recorder *MockWalletServiceMockRecorder
}

// MockWalletServiceMockRecorder is the mock recorder for MockWalletService.
type MockWalletServiceMockRecorder struct {
	mock *MockWalletService
}

// NewMockWalletService creates a new mock instance.
func NewMockWalletService(ctrl *gomock.Controller) *MockWalletService {
	mock := &MockWalletService{ctrl: ctrl}
	mock.recorder = &MockWalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletService) EXPECT() *MockWalletServiceMockRecorder {
	return m.recorder
}

// AdjustUserBalanceOnGivenCurrency mocks base method.
func (m *MockWalletService) AdjustUserBalanceOnGivenCurrency(arg0 context.Context, arg1 int, arg2 string, arg3 float32) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustUserBalanceOnGivenCurrency", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdjustUserBalanceOnGivenCurrency indicates an expected call of AdjustUserBalanceOnGivenCurrency.
func (mr *MockWalletServiceMockRecorder) AdjustUserBalanceOnGivenCurrency(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustUserBalanceOnGivenCurrency", reflect.TypeOf((*MockWalletService)(nil).AdjustUserBalanceOnGivenCurrency), arg0, arg1, arg2, arg3)
}

// GetUserBalanceOnGivenCurrency mocks base method.
func (m *MockWalletService) GetUserBalanceOnGivenCurrency(arg0 context.Context, arg1 int, arg2 string) (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBalanceOnGivenCurrency", arg0, arg1, arg2)
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBalanceOnGivenCurrency indicates an expected call of GetUserBalanceOnGivenCurrency.
func (mr *MockWalletServiceMockRecorder) GetUserBalanceOnGivenCurrency(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBalanceOnGivenCurrency", reflect.TypeOf((*MockWalletService)(nil).GetUserBalanceOnGivenCurrency), arg0, arg1, arg2)
}
