// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eneskzlcn/currency-conversion-service/app/conversion (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	conversion "github.com/eneskzlcn/currency-conversion-service/app/conversion"
	entity "github.com/eneskzlcn/currency-conversion-service/app/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserActiveExchangeOffer mocks base method.
func (m *MockRepository) GetUserActiveExchangeOffer(arg0 context.Context, arg1 conversion.UserActiveExchangeOfferDTO) (entity.UserActiveExchangeOffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActiveExchangeOffer", arg0, arg1)
	ret0, _ := ret[0].(entity.UserActiveExchangeOffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActiveExchangeOffer indicates an expected call of GetUserActiveExchangeOffer.
func (mr *MockRepositoryMockRecorder) GetUserActiveExchangeOffer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActiveExchangeOffer", reflect.TypeOf((*MockRepository)(nil).GetUserActiveExchangeOffer), arg0, arg1)
}
