// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eneskzlcn/currency-conversion-service/app/conversion (interfaces: Repository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	conversion "github.com/eneskzlcn/currency-conversion-service/app/conversion"
	model "github.com/eneskzlcn/currency-conversion-service/app/model"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateUserConversion mocks base method.
func (m *MockRepository) CreateUserConversion(arg0 context.Context, arg1 conversion.CreateUserConversionDTO) (model.UserCurrencyConversion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserConversion", arg0, arg1)
	ret0, _ := ret[0].(model.UserCurrencyConversion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserConversion indicates an expected call of CreateUserConversion.
func (mr *MockRepositoryMockRecorder) CreateUserConversion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserConversion", reflect.TypeOf((*MockRepository)(nil).CreateUserConversion), arg0, arg1)
}

// GetExchangeOfferByID mocks base method.
func (m *MockRepository) GetExchangeOfferByID(arg0 context.Context, arg1 conversion.GetExchangeRateOfferDTO) (model.ExchangeRateOffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeOfferByID", arg0, arg1)
	ret0, _ := ret[0].(model.ExchangeRateOffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeOfferByID indicates an expected call of GetExchangeOfferByID.
func (mr *MockRepositoryMockRecorder) GetExchangeOfferByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeOfferByID", reflect.TypeOf((*MockRepository)(nil).GetExchangeOfferByID), arg0, arg1)
}
